//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: Quote.proto
namespace Inceptum.Messaging.Tests
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quote")]
  public partial class Quote : global::ProtoBuf.IExtensible
  {
    public Quote() {}
    
    private uint _finam_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"finam_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint finam_id
    {
      get { return _finam_id; }
      set { _finam_id = value; }
    }

    private uint _date = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint date
    {
      get { return _date; }
      set { _date = value; }
    }

    private double _last = default(double);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"last", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double last
    {
      get { return _last; }
      set { _last = value; }
    }

    private double _bid = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bid
    {
      get { return _bid; }
      set { _bid = value; }
    }

    private double _bidvol = default(double);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"bidvol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bidvol
    {
      get { return _bidvol; }
      set { _bidvol = value; }
    }

    private double _ask = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ask
    {
      get { return _ask; }
      set { _ask = value; }
    }

    private double _askvol = default(double);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"askvol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double askvol
    {
      get { return _askvol; }
      set { _askvol = value; }
    }

    private double _open = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double open
    {
      get { return _open; }
      set { _open = value; }
    }

    private double _high = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double high
    {
      get { return _high; }
      set { _high = value; }
    }

    private double _low = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double low
    {
      get { return _low; }
      set { _low = value; }
    }

    private double _close = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"close", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double close
    {
      get { return _close; }
      set { _close = value; }
    }

    private double _volume = default(double);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double volume
    {
      get { return _volume; }
      set { _volume = value; }
    }

    private double _value = default(double);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double value
    {
      get { return _value; }
      set { _value = value; }
    }

    private double _chg = default(double);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"chg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double chg
    {
      get { return _chg; }
      set { _chg = value; }
    }

    private uint _chgdir = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"chgdir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chgdir
    {
      get { return _chgdir; }
      set { _chgdir = value; }
    }

    private uint _last_time = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"last_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_time
    {
      get { return _last_time; }
      set { _last_time = value; }
    }

    private double _last_trade_size = default(double);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"last_trade_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double last_trade_size
    {
      get { return _last_trade_size; }
      set { _last_trade_size = value; }
    }

    private uint _trade_count = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"trade_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint trade_count
    {
      get { return _trade_count; }
      set { _trade_count = value; }
    }

    private double _yhigh = default(double);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"yhigh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double yhigh
    {
      get { return _yhigh; }
      set { _yhigh = value; }
    }

    private double _ylow = default(double);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ylow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ylow
    {
      get { return _ylow; }
      set { _ylow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
#pragma warning restore 1591  
